### ISSUE TITLE
无意中发现这好项目，可惜没跑起来

### ISSUE THREAD

**Issue by hejialong1314** [bosima/Swift#1]
应该把使用文档完善一下
管理运行 Swift.exe -b 192.168.1.100 -c 192.168.1.100 -r manager
成员运行 Swift.exe -b 192.168.1.101 -c 192.168.1.100 -r worker
Manager 中是 Jobs 文件夹，不是Job 
希望大哥能完善好基本功能让他跑起来，加油

**Comment by bosima** [comment]
确实还有很多要完善的地方，也是想能好好搞搞，我找时间再整理下

**Comment by bosima** [comment]
已经重构了很多的代码，并迁移到了.NET Core平台，欢迎使用。
